### ISSUE TITLE
Support for Macs Agent in Azure DevOps

### ISSUE THREAD

**Issue by ishansingh-nagra** [renevanosnabrugge/SendEmail-BuildTask#59]
Hi,
I have recently started working on Azure DevOps CI/CD for a RN project. I tried to use this plugin for email notifications, but as my code needs to run on MacOS devices i see error as below.

##[error]The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.

<img width="1339" alt="Screenshot 2024-08-01 at 11 13 59" src="https://github.com/user-attachments/assets/288a247b-7c49-41ba-b145-261919f8a6f0">

**Comment by wesmacdonald** [comment]
This should be resolved with V2 of the extension.

**Comment by kyle-demers-amcs** [comment]
Confirming v2 still doesn't seem to be working:
![Image](https://github.com/user-attachments/assets/4662a5f0-c951-4f95-9dd0-24b432a72ea3)

I'm using a macOS-15 agent in my pipeline.

**Comment by wesmacdonald** [comment]
Let me check, thanks for reporting this.

**Comment by wesmacdonald** [comment]
I have submitted a support request with Microsoft as to why the V2 node version of the task only runs on Windows.

**Comment by kyle-demers-amcs** [comment]
Excellent, I appreciate that 👍

**Comment by wesmacdonald** [comment]
I received a response from Microsoft with a suggestion to resolve the issue. I will be submitting a new PR shortly.

**Comment by kyle-demers-amcs** [comment]
No rush at all, but I saw the PR was merged - just curious how long it typically takes for the latest version to be published/approved by Azure?

**Comment by wesmacdonald** [comment]
Good evening, I have finally completed all my testing with the latest fixes. I should be able to push it out by the weekend. I tested SendEmail@2 on macOS, Linux and Windows hosted agents.

![Image](https://github.com/user-attachments/assets/5caba1cb-78b8-4c6a-be99-0a61ec0001f1)

**Comment by wesmacdonald** [comment]
Pull Request created #67  - bit more work to do on the pipeline prior to publishing to the VS Market Place.

**Comment by wesmacdonald** [comment]
Version 2.0.5 of the extension has been published to the marketplace.

**Comment by kyle-demers-amcs** [comment]
Thanks so much! I'm going to give it a test now

**Comment by kyle-demers-amcs** [comment]
Hello! I forgot to report back. I think this might be an organization issue and not necessarily an issue with the task, but I figured it was worth asking.
When I run the task, it's still running on version 2.0.4 on the macOS agent despite having updated to 2.0.5 in the Azure Marketplace.
It doesn't look like Azure supports specifying 2.0.5 when referencing the task name though. Do you have any idea what could be causing this?
